This is makeindex, version 2.15 [TeX Live 2016] (kpathsea + Thai support).
Scanning style file ./verslag.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file verslag.acn....done (24 entries accepted, 0 rejected).
Sorting entries....done (120 comparisons).
Generating output file verslag.acr....done (22 lines written, 0 warnings).
Output written in verslag.acr.
Transcript written in verslag.alg.
